### ISSUE TITLE
Panelized file only has tracks routed on one copy.

### ISSUE THREAD

**Issue by atroly** [sej7278/kicad-panelizer#13]
I am using KiCad 6.0.2 to generate a panelized version of a simple PCB. The tool generated a 5x4 matrix of boards within the 100x100mm constraints, but when opened with KiCad's standalone PCB editor only the top left PCB was routed, all the others had rats nests. Am I missing something obvious?

**Comment by sej7278** [comment]
no, i see that too, seems to be something to do with the 6.x version, i'll do some digging

**Comment by sej7278** [comment]
can you try now please, looks better now to me!

**Comment by atroly** [comment]
Looks great, thanks. There are still rats nest lines running between the copies, but presumably that won't affect the gerbers.

Thanks again for the super quick fix!

**Comment by sej7278** [comment]
cool, thanks for spotting that!

the rats nest is unavoidable (its kicad trying to join all the boards together!) but is purely cosmetic and won't affect the gerbers.
