### ISSUE TITLE
Doesn't copy Edge.Cuts for non-rectangular boards

### ISSUE THREAD

**Issue by willemcvu** [sej7278/kicad-panelizer#8]
When panelizing a design that has routed and V-scored edges, the script ignores any edges that don't make up the rectangular bounding box of the board.

**Comment by sej7278** [comment]
Not sure how you'd do that really. People tend to use mouse-bites to panelize non-rectangular boards.

**Comment by willemcvu** [comment]
Ah yes, really not sure what my thought process was here at all. I tried panelizing a non-rectangular board and apparently got confused when it didn't work, lol.

**Comment by sej7278** [comment]
I got a panel back from JLCPCB and they made it correctly - with vscores and the customerid on the edge rails, did you get the boards back that you made yet?
