### ISSUE TITLE
Gaps between

### ISSUE THREAD

**Issue by janekdrw** [sej7278/kicad-panelizer#9]
It would be nice to be able to add a small gap between the boards in the panel, as an option.
Useful if prototype PCB made ad-hoc, and then panel is cut by diamond circular saw.

**Comment by ademmler** [comment]
I would like to have such function as a real feature.
Like adding to more v-cuts in a certain distance between the pcbs boards.
My pick&place vendor was asking for this.

rgds Alexander

**Comment by sej7278** [comment]
could you test this [feature branch](https://github.com/sej7278/kicad-panelizer/tree/padding), i've added a `--padding` argument

it creates output like this - obviously  each board becomes bigger so fewer can fit a panel:

![screenshot](https://user-images.githubusercontent.com/817564/182660491-4cbe1dc5-6223-4cfb-ab1c-953b60554679.png)

is that the sort of thing you need?

i had thought of not adding padding to the outside edges, but then your board would be uneven.

**Comment by ademmler** [comment]
Hi Simon,

thx for your quick help!

Padding is a nice feature too - and maybe what [janekdrw]needs. Hence I would keep it.

But it is not what my pick & place vendor asked me for.
He needs to have "adjustable space" + 2 V-Cuts" between each pcb.
I have painted some sketch.

Rgds Alex

![182660491-4cbe1dc5-6223-4cfb-ab1c-953b60554679](https://user-images.githubusercontent.com/6755238/182685714-fde39f4d-a8f4-4542-a8c3-693bf9ce0943.png)

**Comment by sej7278** [comment]
I had a go but couldn't find a nice solution to adding a whole new set of vscores (and it would need padding too).

I've merged the padding feature branch, maybe someone will do a PR with your request Alex....

**Comment by ademmler** [comment]
Hi Simon,

thx for your efforts - very kind.

Regards Alex

**Comment by janekdrw** [comment]
> is that the sort of thing you need?

Yes, thank you for your effort.
result looks like what I expected

I can't test with my boards at the moment, I'm stuck with version 5.x of KiCAD.
